# Generated by Django 5.2 on 2025-05-02 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Формат: до 12 цифр (включая 2 знака после запятой). Пример: 1000.50', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Формат: до 12 цифр (включая 2 знака после запятой). Пример: 1000.50', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
