# Generated by Django 5.2 on 2025-05-03 00:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_budget', '0002_summary_is_closed_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Формат: до 12 цифр (включая 2 знака после запятой). Пример: 1000.50', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_budget.expensecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Формат: до 12 цифр (включая 2 знака после запятой). Пример: 1000.50', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_budget.incomecategory', verbose_name='Категория'),
        ),
    ]
