# Generated by Django 5.2 on 2025-05-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_budget', '0003_alter_expense_amount_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'расход', 'verbose_name_plural': 'расходы'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Категория расхода', 'verbose_name_plural': 'Категории расходов'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'доход', 'verbose_name_plural': 'доходы'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'verbose_name': 'Категория дохода', 'verbose_name_plural': 'Категории доходов'},
        ),
    ]
