# Generated by Django 5.2 on 2025-05-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_budget', '0004_alter_expense_options_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
    ]
