# Generated by Django 5.2 on 2025-05-03 14:39

from django.db import migrations
from my_budget.models import Summary

def recalculate_all_summaries(apps, schema_editor):
    for summary in Summary.objects.all():
        summary.income = Summary.total_income(summary.year, summary.month)
        summary.expense = Summary.total_expense(summary.year, summary.month)
        summary.balance = summary.income - summary.expense
        summary.save()

class Migration(migrations.Migration):

    dependencies = [
        ('my_budget', '0005_alter_expensecategory_name_alter_incomecategory_name'),
    ]

    operations = [
        migrations.RunPython(recalculate_all_summaries),
    ]
