# Generated by Django 5.2 on 2025-05-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_budget', '0008_expensecategory_created_at_incomecategory_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Сводка', 'verbose_name_plural': 'Сводку'},
        ),
    ]
