# Generated by Django 5.2 on 2025-05-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_budget', '0009_alter_summary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Сводку', 'verbose_name_plural': 'Сводки'},
        ),
    ]
